name: Frontend CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'FrontEnd-Git/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'FrontEnd-Git/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install Dependencies
      working-directory: FrontEnd-Git
      run: npm install
      
    - name: Build
      working-directory: FrontEnd-Git
      run: npm run build
      
    - name: Run Tests
      working-directory: FrontEnd-Git
      run: npm test

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Deploy Frontend
      run: |
        echo "Deploying frontend application..."
        # Add your deployment steps here
        exit 0